### ISSUE TITLE
support external storage

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#104]
Look into using SDL_AndroidGetExternalStoragePath() for save games and plugins.

**Comment by mike-lloyd03** [comment]
This would be great so I could share a pilot file between my phone and my laptop via Nextcloud.

**Comment by FONZACUS** [comment]
would be awesome. while i havent tried the import button for plugins (supposedly it works, but can derp with irregular zip structure) im doing it manually with root
itd greatly help the more general users

**Comment by MonkeyMatrix** [comment]
> while i havent tried the import button for plugins (supposedly it works, but can derp with irregular zip structure)

The import button for plugins works well for me. I am able to import plugins which have the files in the root of the zip, but I can also import plugins which have a sub-directory before the plugin files. The removal of either type also works.

> im doing it manually with root itd greatly help the more general users

The irregular zip structure seems to have been fixed for some time now, unless there is a different structure I have not come across #41. You shouldn't have to move things around with root, so I would suggest trying out the import button again.

**Comment by Lumostr** [comment]
The plugin import button doesn't work for me either.. on the latest version till today

**Comment by thewierdnut** [comment]
> The plugin import button doesn't work for me either.. on the latest version till today

For any plugin? Or do you have a specific plugin it fails on?
