### ISSUE TITLE
Minor / Non urgent UI issues.

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1- The plugin section does not have a scroll or extended section feature, causing the plugin list to overlap with the interface buttons.
![Screenshot_20231004-085400](https://github.com/thewierdnut/endless-mobile/assets/89931675/4127c920-fc87-43d6-8940-d4b0b3afe65d)

2- Tapping on an outfit's or ship's stats does not give a description of the stat as it was previously done.
![Screenshot_20231004-085518](https://github.com/thewierdnut/endless-mobile/assets/89931675/a3ecbe0d-e5fb-48e6-b6c3-ab8fbffd16ba)

### Steps to Reproduce

1-
   1. Install a lot of plugins.
   2. Go to the "Plugins" menu.
   3. See error.

2-
   1. Tap on a ship/outfit.
   2. Tap on one of its stats.
   3. See error.

### Expected Behavior

1- The UI doesn't overlap with the plugin list.

2- The description of the stats is shown.

### Screenshots

/

### Link to save file

/

### Device type

Overclocked Samsung Tab S2 9.7 Black

### Game Version

Latest continuous as of 4/10/2023. (dd/mm/yyyy)

### Additional Information

/

**Comment by thewierdnut** [comment]
These are actually two separate bugs. 

The plugin list is a bug that affects upstream as well, though I can't find a specific issue there for it. 

The outfit tooltip is a botched merge, and I'll push a fix for that shortly.
