### ISSUE TITLE
Can't delete plugins when the plugin name is not the folder name

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#112]
### Problem Description

Why does this happen?
Has it happened to you before?
Is it an issue only found with this specific plugin?
Couldit be an issue with the plugin switch-off feature?

![Screenshot_20231006-143645](https://github.com/thewierdnut/endless-mobile/assets/89931675/5c63f0c6-c5b7-4254-8c21-adb4b8b6d150)

### Related Issue Links

/

### Desired Solution

/

### Alternative Approaches

/

### Additional Context

I deactivated this specific plugin, played the game with the plugin off for a while, then activated it again. After a while I chose to remove it but it gives error every time, can't remove it.

**Comment by thewierdnut** [comment]
I would love to see the internal state of the plugin folder. 

What version do you have installed? Do you have experience using adb?

**Comment by YiffLord** [comment]
> I would love to see the internal state of the plugin folder.
> 
> What version do you have installed? Do you have experience using adb?

Version installed is the latest continuous aviable. No experience using adb whatsoever.

**Comment by thewierdnut** [comment]
Uhg. The name of the plugin is no longer its folder name, and it's  trying to delete the plugin using the plugin name, rather than the plugin path. 

I'll need to fix this.
