### ISSUE TITLE
Incorrect Version Shown in MenuPanel

### ISSUE THREAD

**Issue by MonkeyMatrix** [thewierdnut/endless-mobile#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At the bottom right of the MenuPanel, the version given does not line up with the actual version shown in the credits.

### Steps to Reproduce

Open Endless Sky Mobile
Look at the bottom right of the screen.
The text should currently be "v0.9.14-21-38"

### Expected Behavior

The text should currently be "v0.10.3-38"

### Screenshots

N/A

### Link to save file

N/A

### Device type

Lenovo Tab M10 Plus 3rd Gen, Pixel 4a

### Game Version

F-Droid 0.10.3-38

### Additional Information

Git describe: [android/app/jni/src/CMakeLists.txt](https://github.com/thewierdnut/endless-mobile/blob/android/android/app/jni/src/CMakeLists.txt#L60)

It seems the newer releases are not tagged the same as older releases. I forked and "released" with a tag (v0.10.3-38), which gave the correct output of "v0.10.3-38." It seems the latest matching tag is v0.9.14-21, and -38 (the mobile version) is appended. It looks like you want to separate the version of endless sky from the version of the mobile port, which I did not do in the forked "release" to my knowledge.

Latest --match release: [thewierdnut/endless-mobile v0.9.14-21](https://github.com/thewierdnut/endless-mobile/tags?after=30)

The fork: [MonkeyMatrix/endless-mobile](https://github.com/MonkeyMatrix/endless-mobile)

**Comment by thewierdnut** [comment]
Is this a build you made? That version string is cached in CMakeCache.txt, so you need you remove and re-run cmake

**Comment by MonkeyMatrix** [comment]
I got the build from F-Droid. Should I try the debug?

**Comment by thewierdnut** [comment]
The version is constructed using two `git --describe` commands. If you are going to tag your own builds using your own rules, then you probably need to modify the code here:

https://github.com/thewierdnut/endless-mobile/blob/android/CMakeLists.txt#L26-L34

**Comment by MonkeyMatrix** [comment]
I just made that one to test git describe since I am new to git and github, and I was unsure from where it was pulling the version numbers. I am sure I used something different than what you use in this repository, but I still remember seeing an incorrect version at the bottom right of the latest F-Droid version in the main menu. Does your installation show 0.10.3-38 (or higher depending on what you are doing)? Is there anything else you want me to try?

**Comment by thewierdnut** [comment]
I just confirmed that the f-droid release generated the wrong version string. I'll have to figure out what happened there. 

EDIT:
Actually, I'm pretty sure I know what happened. f-droid is pulling my android branch, but I haven't been pushing the master tags to the endless-mobile repo, because my local repo already has them. This means that f-droid is only aware of the upstream tags to the point where I initially created the fork. I'll have to generate that version string some other way.
