### ISSUE TITLE
Request: Some more (possibly customizable) buttons on the UI

### ISSUE THREAD

**Issue by Bearroneous** [thewierdnut/endless-mobile#114]
### Problem Description

Hello, firstly I hope this is in the right place and is ok to ask.

Would it be possible to have a few more buttons in the main UI, for things like boarding the nearest ship, stopping, targeting asteroids etc? Similar to the already present Attack, Deploy, etc buttons in the bottom-right. Like what gestures do, but for some on screen buttons.

If possible these buttons could be turned on/off in the options for those that use a smaller screen and want to avoid clutter, but still select the few extra buttons they want.

Or a default handful/placement of buttons which the user could choose the action for, just like setting a gesture.

I am playing on a tablet and while the gestures for some of these actions are fine, I feel like I am missing the precision that just a few more proper buttons could provide. 

I don't mind the gestures and they are a great way to shortcut stuff on a touchscreen, but sometimes they do things like select ships if I finish the swipe over the ship, or if things are busy I might have to draw the gesture a few times to get right, and of course even just doing the gesture in the screen space makes my flagship want to face that direction.

One thing I continue to struggle with is directing my fleet to harvest flotsam, it turns off constantly while doing other things and then I need to gesture again to turn it back on. A button that changes colour when harvesting is on/off, and touch it to turn back on would reduce the amount of gesturing I do massively. 
Or even an option in the settings to 'force harvest flotsam to on' when there isn't combat happening (when the red alert symbol is on screen in the top left.)

### Related Issue Links

-

### Desired Solution

A few more optional/customizable buttons for different actions would be greatly appreciated. And a 'force harvest flotsam' option.

### Alternative Approaches

-

### Additional Context

By the way, thank you so much for making this port, I found Endless Sky a couple months ago and have been greatly enjoying playing it on a tablet.

The only other feature request I would like to make, but is probably something the main game would need to implement, is a half/25% speed mode, like the fast-forward speed mode. Because I do find combat rather difficult sometimes in the larger engagements on a touchscreen and slowing down a bit to better target ships and pilot my own would be a godsend.

**Comment by thewierdnut** [comment]
The buttons are fully customizable via plugins. 

You may want to give https://github.com/zuckung/endless-sky-plugins/tree/main/myplugins/additional.command.buttons a try

**Comment by Bearroneous** [comment]
Thank you so much for pointing me in the right direction!
I will have to give it a try. I haven't used plugins yet and am not sure how to on android as I can't access where the game files are. But I will have a look!
Edit: Woo! I didn't realise you had added an 'import' to the plugin screen. I was worried I'd be delving into the files but you've made it so simple. Thanks!

**Comment by thewierdnut** [comment]
on the preferences->plugins tab, there is an import button. just feed it a zip file containing your plugin, and it should import just fine. 

![image](https://github.com/thewierdnut/endless-mobile/assets/9004013/f3fdb24f-89de-4110-8145-4caa32c42471)
