### ISSUE TITLE
Lagging when Jumping

### ISSUE THREAD

**Issue by jcgaming-official** [thewierdnut/endless-mobile#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The game is keep lagging when I click Jump

### Steps to Reproduce

Play and jump

### Expected Behavior

Smooth

### Device type

Infinix Note 12G96

### Game Version

0.10.3-38

**Comment by thewierdnut** [comment]
Unable to reproduce with the default settings

What do you have for the following settings?
* Render motion blur
* VSync
* Reduced Graphics
* Draw background haze
* Draw starfield
* Parallax background
* Show hyperspace flash
* Extended jump effects

**Comment by MonkeyMatrix** [comment]
Turning render motion blur off fixed this for me. I noticed the blur of stars when jumping, so I did this first.

**Comment by jcgaming-official** [comment]
> Turning render motion blur off fixed this for me. I noticed the blur of stars when jumping, so I did this first.

It works. Thank you
