### ISSUE TITLE
Starting in reverse landscape glitches input location

### ISSUE THREAD

**Issue by asl97** [thewierdnut/endless-mobile#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When starting the game in reverse landscape, input is offset by a bit

### Steps to Reproduce

1. Start app with phone in portrait, note which direction the app open
2. fully close the app, ensure "Lock Orientation/rotation" is selected
3. Reopen the app with the phone in the other direction (reverse landscape)
4. See the black bar on the camera side and top of screen
5. Notice input is slightly off

note: it seem to fix itself after opening the recent menu and reentering the game

There also issue with reproducibility(?), to force it to appear, try opening the app in the 'correct' orientation and force closing before opening it in 'reverse' orientation, repeat a few times?

### Expected Behavior

The app open properly with no black bar like when opening while the phone is in portrait or the correct landscape and input not offset

### Screenshots

https://github.com/thewierdnut/endless-mobile/assets/4752645/1f6759b2-7c89-4497-b0d2-aaba7985f27b

### Device type

POCO F3

### Game Version

0.10.4.39

**Comment by thewierdnut** [comment]
This is AWESOME! 

I've seen this bug on occasion, but I've been avoiding fixing it because I've never found a way to reliably reproduce it. The steps you outline work great!

**Comment by MonkeyMatrix** [comment]
I have also seen this before, but I was also unable to reproduce it. Thank you!

**Comment by thewierdnut** [comment]
Stupid SDL_StupidEventFilter flushes the stupid event queue, wiping out the stupid screen resize events. Stupid. Stupid Stupid. 

Moved the Event filter prior to the event queue being initialized, which seems to fix it.
