### ISSUE TITLE
No Way to Repair Escorts

### ISSUE THREAD

**Issue by ghost** [thewierdnut/endless-mobile#12]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

It seems that if an escort is disabled, there is no way to help it. 

### Steps to Reproduce

1. Get into a fight that disables the escort
2. Select the escort and see there's no way to repair it

### Expected Behavior

There's a way to repair it.

### Operating System

Android 12

### Game Source

Other (please describe)

### Game Version

0.9.16.1-28

### Additional Information

Game Source is F-Droid

**Comment by johndh** [comment]
There's not a "board" or "dock" button, but have you tried tapping on the disabled escort when it's highlighted? It's been working for me. You can also board disabled enemies this way.

**Comment by thewierdnut** [comment]
I've confirmed. If you click on a disabled ship, you will either repair it or board it.

**Comment by asl97** [comment]
I think there should be a dedicated button for 'b', if I remember correctly, it also handle refueling escorts and it's not always easy to find disabled ship ether
