### ISSUE TITLE
gestures "not set" isn't saved after restart

### ISSUE THREAD

**Issue by zuckung** [thewierdnut/endless-mobile#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I set the gestures to "not set", that configuration stays only for the current game. On app restart, all gestures are restored.

That's really a pain, cause I do a lot of gestures by accident.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Save the status if the gestures.

### Device type

galaxy tab a6

### Game Version

0.10.6 latest

**Comment by ZeroTwo002-ES** [comment]
I also got that problem, every time i try to move my ships on android, and accidentally do some gesture, the ship will do the command, even tho i not intentionally use it at all, so i want to have permanent not set gesture whenever i restart the game

**Comment by lithium-hypercube** [comment]
I have found a workaround: unset all gestures, set forward thrust to (for example) the O gesture, click Back to Menu and then click Quit. Drawing O seems to do nothing and the ship can be controlled normally.
