### ISSUE TITLE
selecting multiple ships in outfitter, shipyard, etc

### ISSUE THREAD

**Issue by johndh** [thewierdnut/endless-mobile#15]
### Problem Description

In the desktop version, you can select several ships at once to buy and sell outfits, or sell multiple ships at once.

### Related Issue Links

N/A

### Desired Solution

Long-press on ships to multi-select

### Alternative Approaches

Double tap, or any other suitable gesture

**Comment by diggernet** [comment]
Related to this, I just had an NPC tell me I can buy outfits to cargo. None of the three methods he described work. Probably the easiest one to implement would be having no ship selected in the outfitter screen. Tapping on an already-selected ship could unselected it, and then purchases would go to cargo.
