### ISSUE TITLE
Scroll Feature for Info Screen

### ISSUE THREAD

**Issue by TraipsingShadow** [thewierdnut/endless-mobile#17]
### Problem Description

First off, I wanted to say thanks for making this port!

I actually found this game while scrolling endlessly (heh) through F-Droid. I never knew it was a port of a PC game until recently. So my concern strictly relates to my experience here. I do not know whether or not this problem persists in the PC version.

In any case, as the title says, I've run into a problem with regards to my ships. I usually never sell my ships and prefer to just park them in a random star system. As to *why* is irrelevant but because of that, I have run into an issue where I can no longer see all of my ships.

![wanna see more of my ships - scroll please!](https://user-images.githubusercontent.com/70948121/203138891-90f7adb3-5946-4036-a9b3-5346589489bf.png)
(*Caption: "Where did all my other ships go?! How will I know which ships are in what system?"*)

The Info screen is very helpful in figuring out where is which, but as the image above shows, the rest of my fleet has gone missing (from the screen)!

The normal instinct is to scroll using one finger to drag it. It is present in the Story left panel that pops up so it should work... *right?* No luck.

Alright, how about with two fingers? Maybe it's designed that way... *nope*. The rest of my fleet remains invisible from the Info screen.

### Related Issue Links

N/A

### Desired Solution

Introduce a scrolling behavior present in the other UI elements such as the Story pop-up panel.

### Alternative Approaches

No other way to view what system a ship is parked on.

**Comment by thewierdnut** [comment]
I've had the same headache. That UI is complicated enough that I haven't looked at it too much yet. This is similar to issue #14, except that I think that this would be a problem upstream as well, and may be better addressed there.

**Comment by thewierdnut** [comment]
This needs to be addressed upstream.

**Comment by thewierdnut** [comment]
https://github.com/endless-sky/endless-sky/issues/8472
