### ISSUE TITLE
Website linked in F-droid package

### ISSUE THREAD

**Issue by asl97** [thewierdnut/endless-mobile#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

F-Droid package's website is linked to official endless sky website instead of this fork github page

### Steps to Reproduce

1. Click F-droid logo
2. Click website link
3. Link open official endless sky website that makes no mention of an android version

### Expected Behavior

Link open this github project page

### Operating System

Android 12

### Game Source

Other (please describe)

### Game Version

NA

### Additional Information

It's fine for this fork github page to link to the official website but it doesn't feel right to link it directly within a forked app page on an app store

It sort of imply official support and currently upstream doesn't seem keen on adding android support anyway base on https://github.com/endless-sky/endless-sky/pull/6689

Don't get me wrong though, this is a much better android experience than via termux or the web version from the first look at it.

**Comment by thewierdnut** [comment]
I think there is a discussion to be had about whether people clicking on the website are looking for information about the game or information about the project. I agree with you however about mis-attributing the source of this fork to the upstream project, and I've submitted a request to f-droid to fix this. 

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12149

**Comment by asl97** [comment]
I see upstream has merged.

Looking at other forked project on f-droid, most seem to leave the website empty unless they actually has a website, example include but not limited to shattered pixel dungeon, openttd, freeminer, tux rider, opsu!

It should be fine to have the website be the same link as the source, I am sure I seen some before but can't recall any at the moment.
