### ISSUE TITLE
stuck on planet due to heat

### ISSUE THREAD

**Issue by johndh** [thewierdnut/endless-mobile#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This could be considered more of a missing feature than a bug. I looted the heat shunt from a ship before capturing it (I usually loot the best outfits before capturing, in case the ship gets destroyed before I land) and landed on a planet with no outfitter. The heat was too much, and I would have been able to access the fleet info to disown the ship on the desktop version, but there doesn't seem to be a way to do this on mobile, so I ended up having to revert to a previous save.

### Steps to Reproduce

Try to take off from a planet with no outfitter, with a ship in your fleet with too much heat, or any other condition that would make it impossible.

### Expected Behavior

Some ability to get to the info screen from here, or maybe any "can't take off with this ship" dialogs could come with a "park" button for the relevant ship?

### Screenshots

![Screenshot_20221128-172058](https://user-images.githubusercontent.com/692397/204401971-9af0ce46-4c21-4f97-963a-3ac27cf7f934.png)

### Link to save file

[Maverick Bleak_exported.txt](https://github.com/thewierdnut/endless-mobile/files/10108346/Maverick.Bleak_exported.txt)

### Operating System

Android

### Game Source

Other (please describe)

### Game Version

0.9.16.1

**Comment by thewierdnut** [comment]
You can access the Info panel via the Job Board (unintuitive, I know), but that won't help you if you are on a planet without a spaceport. 

As far as abandoning or parking the ship from the problem dialog, this is probably a feature request for upstream. Try posting an issue upstream at https://github.com/endless-sky/endless-sky/issues

**Comment by thewierdnut** [comment]
A direct button for the info page will now appear if there is no spaceport.
