### ISSUE TITLE
Asteroid mining

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Need a way to mine asteroids. The current "Fire" button will not target them. 

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

To be able to target and fire on asteroids. 

### Operating System

asdf

### Game Source

Other (please describe)

### Game Version

asdf

**Comment by thewierdnut** [comment]
Fixed by 57abade89feb4d8669b5d48a0fc642ecfa2a44df

**Comment by mount2010** [comment]
I'm not sure how to target an asteroid so that I can mine it? It seems like tapping on anything that isn't a ship makes me move there instead.

**Comment by thewierdnut** [comment]
You need an asteroid scanner. Most outfitters have it.

**Comment by mount2010** [comment]
Ah, on desktop Endless Sky, you can mine without needing an asteroid scanner. I was going to do that with a fighter start to earn my initial cash. Consider that?
