### ISSUE TITLE
Park an individual ship

### ISSUE THREAD

**Issue by daisy613** [thewierdnut/endless-mobile#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

How do I park a single ship? Only park/unpark all button is available.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Park a single ship

### Device type

Galaxy S20

### Game Version

0.9.16.1 PR v29

**Comment by thewierdnut** [comment]
Use the "Ship Info" tab. You can navigate between ships using the "Previous" or "Next" button, or on the Player Info tab, you can double-tap on the ship name to switch directly to the info for that ship.
