### ISSUE TITLE
unable to import large plugins

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

app crashes when loading a large plugin 

### Steps to Reproduce

Try to import a large plugin, such as the large freight plugin. The app crashes. 

### Expected Behavior

successful import

### Device type

na

### Game Version

latest master

### Additional Information

The O/S is killing the app because it runs out of memory. This will probably vary from device to device. This is probably occurring because the java code and the c++ code copy the file contents into memory before processing it. The api needs to be modified to stream the file over instead of passing it all at once.

**Comment by Pseudomyrmex** [comment]
I still have this problem even with the newest version. Everything above roughly 60MB crashes the game. For example Galactic War (137MB) or "A galaxy far far away" (687MB).

**Comment by thewierdnut** [comment]
Can you link those two plugins?

**Comment by Pseudomyrmex** [comment]
Sure, no problem

https://github.com/1010todd/Galactic-War

https://www.moddb.com/mods/endless-sky-a-galaxy-far-far-away/news/the-consistency-update-v04-alpha

**Comment by thewierdnut** [comment]
Is this crashing the game on startup, or when it is loading the plugin? 

Also, what is the exact version of the game you have installed?

**Comment by Pseudomyrmex** [comment]
It crashes as soon as I select the zip file which contains the mod. I made sure the data is freshly packed and has no more subfolders then necessary.

I am currently using version 0.9.16.1-30 of the apk, running on Android 12, SD 888+

**Comment by thewierdnut** [comment]
By "crash", do you mean "The game exits", or "there is a black screen, and the game doesn't come back"

**Comment by Pseudomyrmex** [comment]
The game exits right back to the homescreen.

**Comment by thewierdnut** [comment]
My device was able to unzip both the "Galactic-War" and "A galaxy far far away" plugins successfully. However, each of these plugins has (separate) issues. 

The "Galactic-War" plugin that I downloaded from its github release page does not have a nested folder within its zip file, and instead contains all the plugin folders in its root directory. The plugin loader does not expect that. My device unzipped the plugin, but after a restart, the plugin was still not visible. Once I modified the plugin zip, it loaded and played correctly. I have created bug #41 to address this. 

The "A galaxy far far away"  plugin unzipped properly, although the app showed a black screen for several minutes while it was unzipping. Once I restarted though, the game was unable to load, even in Reduced Graphics mode. The problem here is that the plugin is simply too big. Once all the graphics are uncompressed and loaded, it is an additional 3.3 gig of data on top of the 2 gig the base game already requires. At this point, my 6 gig device was unable to finish loading the game before the operating system shut it down for using too much memory. I have created request #40 to address this. 

At this point, I am unable to reproduce the described symptom of the game exiting after selecting the plugin. The next step would be to get an adb log dump if you know how to retrieve it. 

Also, how much ram does your device have?

**Comment by Pseudomyrmex** [comment]
I feared it would be device specific.

Also I nested the galactic war plugin to the required form, but still no luck. Maybe the RAM management of my device is too aggressive although I can't find a way to change that.

My device has 16 GB of RAM and over 250GB of free storage.

I will try to create an adb log as soon as possible, I got all tools installed but never tried this specific task.

**Comment by thewierdnut** [comment]
hm... presumably you should be able to load them, but lets fix the crashing issue first.

**Comment by Pseudomyrmex** [comment]
The newest debug version of the app is able to load both mods with no problem other then a short black screen.
Now I just have to figure out why this version is so horribly pixelated...

**Comment by thewierdnut** [comment]
Do you have "Reduced graphics" turned on under Preferences->Settings->Performance? 

It is supposed to turn on automatically when it detects less than 4 gig of ram, but maybe its broken (or the operating system is lying to it)

**Comment by Pseudomyrmex** [comment]
Ah, yes that's it. Sorry for that.

I will still create a log dump so we know what the problem was.

**Comment by thewierdnut** [comment]
Actually, don't bother. Release 30 doesn't have the large zipfile fix, so you definitely would have run into that.

**Comment by Pseudomyrmex** [comment]
Ok, I figured because the bug was closed it is already integrated in the new release. Sorry for the trouble and thanks for the help.
But at least I learned how to create log files for the next time I run into bugs. :)

**Comment by thewierdnut** [comment]
On a mostly unrelated note, I just pushed a new build that should fix the defaulted Reduced graphics mode as well.
