### ISSUE TITLE
Bulk buy and sell

### ISSUE THREAD

**Issue by TheFurnace** [thewierdnut/endless-mobile#36]
### Problem Description

Currently items like "Gatling ammunition" are very hard to buy/sell. I accidentally acquired a bunch via selling a captured ship and there's 2000 ammo in my ship now.

### Related Issue Links

No related issues afaik.

### Desired Solution

Perhaps a toggle button that indicates the amount of items to buy/sell. It could toggle through 1-10-100-1000

### Alternative Approaches

Alternatively a way to input Ctrl/shift would work.

**Comment by thewierdnut** [comment]
If you are just looking for a way to sell extra outfits/ammo you can't use, you can use the trading page for that. 

Otherwise, I agree. The outfit page has too much reliance on the keyboard. See issue #24

**Comment by TheFurnace** [comment]
Thanks for the workaround, fortunately gatling ammo is basically the only unit where this is a problem, still annoying.
