### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by danxnader** [thewierdnut/endless-mobile#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have downloaded this version of the game from F-Droid on my Gome K1 running on Android 6.0.1. (international version). There were no incompatibility warnings of any sort.
After startup, phone goes into landscape mode and screen turns black. After a few seconds app crashes and i get "Endless Sky exited unexpectedly" pop-up.
I tried cleaning cash and reinstalling, no results so far.

### Steps to Reproduce

1. Open application.
2. It crashes after a few seconds.

### Expected Behavior

Game is not supposed to crash.

### Device type

Gome K1

### Game Version

v0.9.1.16.1-30

### Additional Information

Note that there are two stock versions of Android for my phone: international and chinese. They differ quite heavily, and i am using international one.

**Comment by thewierdnut** [comment]
Its hard to tell what is going on with a crash like this without some adb logcat output.

**Comment by thewierdnut** [comment]
What android version are you running? A casual google search on your device type says 6.1 Marshmallow, which has a known issue where the sdl path calls return a different value for older android releases. 

I'll try and cut a new continuous build later today to see if this fixes it.

**Comment by thewierdnut** [comment]
When you get a chance, can you try the latest continuous build when it finishes? I've added some workarounds for the path handling code in android marshmallow in commit f0740be7600410142374c47cc8ad74fb6fcdcfa4

**Comment by danxnader** [comment]
Checked it, seems to be working fine
