### ISSUE TITLE
missions not continuing

### ISSUE THREAD

**Issue by johndh** [thewierdnut/endless-mobile#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes when loading a game, a campaign mission will be missing.

### Steps to Reproduce

Complete a step in a campaign mission, such as landing on Green rock with the monk. Click through the dialogs, then exit the game. When you return, the next campaign mission is not there, and the campaign cannot be continued.

### Expected Behavior

Perhaps the game is saved after the previous mission is completed but before the next one is added?

### Link to save file

[Waverly Linden_exported.txt](https://github.com/thewierdnut/endless-mobile/files/10455932/Waverly.Linden_exported.txt)
[Waverly Linden_exported_previous.txt](https://github.com/thewierdnut/endless-mobile/files/10455939/Waverly.Linden_exported_previous.txt)

### Device type

Moto 5G Ace

### Game Version

0.9.16.1

### Additional Information

I suspect this is related to #13 and the new save behavior.

**Comment by thewierdnut** [comment]
So far, I have been unsuccessful at reproducing your second save file from your first save file. If I exit or kill the game after I land, then when I restart, it always brings the next mission dialog up. 

I'll check the mission logic against the save logic. Its probably ok to re-order them or something. 

If you run across this again though, your save file still has the triggers set for landing on greenrock. If you leave and then re-land by paying a tribute, it will re-trigger the mission dialog.

**Comment by johndh** [comment]
I'm not exactly sure how to reproduce it. That just seems to be the general pattern of when I've noticed it. If it still has the trigger, is it saving before the first mission is completed, or is it completing the mission and not removing the trigger when it saves?

**Comment by thewierdnut** [comment]
This may be upstream https://github.com/endless-sky/endless-sky/issues/3746

If so, it should be fixed now.

**Comment by ziproot** [comment]
I think this is the same issue as #42
