### ISSUE TITLE
Latest CI Build doesn't include APK file

### ISSUE THREAD

**Issue by Lawrence-Krystal** [thewierdnut/endless-mobile#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There's no apk file for latest ci build.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

APK file

### Device type

Android 9 Device

### Game Version

v0.9.16.1-30

### Additional Information

I'm new to GitHub, just found this game. Already in love. Reminds me so much of starsector. My PC broke so I'm playing this now. Hope to get latest build so I can play as a miner.

**Comment by thewierdnut** [comment]
Looks like it generated correctly: https://github.com/thewierdnut/endless-mobile/actions/runs/4066535077

In general you can go to https://github.com/thewierdnut/endless-mobile/releases, and the latest continuous build should be listed right on top.

**Comment by Lawrence-Krystal** [comment]
Weird, I don't see the apk files like the previous ones only 2 zip files

Never mind, I used desktop site and now I can download it weird...

**Comment by thewierdnut** [comment]
yeah, don't look under the "assets" dropdown, click on the "actions/runs" link provided as part of the comment

**Comment by Lawrence-Krystal** [comment]
Thanks!
