### ISSUE TITLE
Massive performance hit in latest CI build

### ISSUE THREAD

**Issue by Lawrence-Krystal** [thewierdnut/endless-mobile#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I know it's a pre-release build but dang, it doubled CPU usage. Dunno if it's a leak or what not. But my phone slowly comes to a halt after playing for an hour.

### Steps to Reproduce

Play the latest CI build.
Notice CPU/GPU usage on top.

### Expected Behavior

Same usage as stable.

### Screenshots

STABLE
![stable](https://user-images.githubusercontent.com/125222547/218457652-2fa01061-5504-4ac0-a23d-2027b19c0423.jpg)
CI BUILD
![CI build](https://user-images.githubusercontent.com/125222547/218457662-50b42d9f-d748-4511-8da6-70b7ae69432b.jpg)

### Device type

Android 9 Device

### Game Version

Latest CI

**Comment by Lawrence-Krystal** [comment]
I'm going to try previous ci builds and hope I get better performance, but i thought I should post this anyways.

**Comment by Lawrence-Krystal** [comment]
Ok so I figured it was the plugin I was using, but it was fine in the stable. Whenever I use a plugin in the CI builds it kinda just turn the game into Superhot. I'm currently using Mega Freight and Becca's endless expansion. I'm gonna start a new game without plugins see if that works better.


(Edit)
Found a workaround, not sure if this causes some of the plugins to "not load” some content. But if you start a vanilla ( no plugins) game then load the plugins. It performs so much better. Like not even reaching 40 CPU. I guess this is a plugin issue...

**Comment by thewierdnut** [comment]
I'm actually surprised if you got those two plugins loaded. without the patch in 53a9868 (which isn't in build 30), the app should have crashed trying to load those plugins (though it depends on how much ram your device has). 

If you got a partial load on those plugins, it may have reported them installed, but I doubt most of the larger assets would have been worked. 

Did you re-install those plugins after installing the latest continuous?

**Comment by Lawrence-Krystal** [comment]
> I'm actually surprised if you got those two plugins loaded. without the patch in [53a9868](https://github.com/thewierdnut/endless-mobile/commit/53a9868fcc311277aa86ccd472d1cbe7162f1883) (which isn't in build 30), the app should have crashed trying to load those plugins (though it depends on how much ram your device has).
> 
> If you got a partial load on those plugins, it may have reported them installed, but I doubt most of the larger assets would have been worked.
> 
> Did you re-install those plugins after installing the latest continuous?

Yeah the workaround I did probably didn't load most assets. My phone has 6gb of RAM so I dunno why it would be a problem. Though after reloading the game and save file it definitely did load everything as it's back to 260% Cpu

**Comment by Lawrence-Krystal** [comment]
Ok, I'm gonna load the plugins in the stable build again and check whether it's just because it wasn't loading properly. I'm gonna post if there's differences.

**Comment by Lawrence-Krystal** [comment]
> Ok, I'm gonna load the plugins in the stable build again and check whether it's just because it wasn't loading properly. I'm gonna post if there's differences.

Alright, it seems like it loaded everything in the stable build. Runs smoother as well. Although it does peak at 100% CPU it doesn't bog it down. 
![Screenshot_2023-02-13-23-23-15-82](https://user-images.githubusercontent.com/125222547/218499334-f1e624ca-e6c4-48e7-8c74-49c197006406.jpg)
![Screenshot_2023-02-13-23-23-33-30](https://user-images.githubusercontent.com/125222547/218499351-336ee31f-5672-49f3-b41d-402b113bdcd4.jpg)
![Screenshot_2023-02-13-23-21-04-29](https://user-images.githubusercontent.com/125222547/218499356-54eade7d-f687-4841-a0a3-360341db06ec.jpg)
![Screenshot_2023-02-13-23-21-26-34](https://user-images.githubusercontent.com/125222547/218499365-301dbadd-3fb7-4de0-8890-441c1aa1aac2.jpg)

**Comment by Lawrence-Krystal** [comment]
just gonna run vanilla maybe Becca's for now. I hope it gets fixed, cause I really want those massive mining freighters :D
Did notice that civs weren't using the mining ships. Also there were very little mining missions, but they were there.

(Small update) Just downloaded a bunch of plugins, tried em 1 by 1 then added more when it worked fine. Seems like so far I can run; lost in the midnight, Becca's, kinetic weapons, sensors. If I add anymore (even small ones like sensor) it goes back to unplayable. Right now even in crowded systems. It runs smoothly at 55 CPU usage taking up 2gb of my 6gb ram. Even tho lost in the midnight is bigger.

Keep up the good work!

**Comment by thewierdnut** [comment]
Keep in mind that endless sky (by which I mean the upstream project) has a nasty habit of loading all the images uncompressed into memory. That can add up really fast. The main reason I haven't pushed a new stable build is that if you exceed your device's limits, then it will crash on startup and there is no way to recover without wiping your app cache (and losing your saves) or rooting your device. 

I am working on some code that will auto-recover from an out-of-memory condition, but it isn't ready yet.

**Comment by Lawrence-Krystal** [comment]
Good luck, I hope it comes soon as I want to play with more plugins ;)
