### ISSUE TITLE
Text goes off UI.

### ISSUE THREAD

**Issue by Lawrence-Krystal** [thewierdnut/endless-mobile#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Text for plugins/descriptions goes off the UI and no way to scroll down.

Is it possible to add a way to scroll down?

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Wrap text

### Screenshots

I know... I'm crazy, but it runs well and doesn't use much memory (I compressed most of the ships texture)
![Screenshot_2023-02-14-23-55-05-42](https://user-images.githubusercontent.com/125222547/218790415-072613a9-10d6-453d-8425-ad83c0911158.jpg)

### Device type

Android 9/6GB device

### Game Version

Latest CI

### Additional Information

Hi again!

**Comment by Lawrence-Krystal** [comment]
I managed to install everything I wanted. Still running smoothly. But ram usage oof. I only have 1.2gb free after the game loads. I wonder what will happen in crowded systems lol.
![Screenshot_2023-02-15-00-13-39-69](https://user-images.githubusercontent.com/125222547/218794819-72965845-bdea-44a9-a083-fbddd7445670.jpg)
![Screenshot_2023-02-15-00-13-50-94](https://user-images.githubusercontent.com/125222547/218794827-f01932d3-6f8e-410e-8992-75565a7cbf14.jpg)

**Comment by thewierdnut** [comment]
This problem occurs upstream as well, and needs to be fixed there.
