### ISSUE TITLE
Afterburners

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#47]
### Problem Description

Since the movement is controlled by tapping and holding on the screen, and there isn't a UI button to use afterburners, they are completely useless in normal scenarios. Afterburners can be used but to do so the engines of the ship have to be removed, causing it to run only by the afterburner. 

### Related Issue Links

No links provided, sorry.

### Desired Solution

Adding a UI button to toggle on and off the afterburner: When toggled on, if the ship moves it will do so with the afterburner working. If it is toggled off, the ship moves only by using the engines. 

### Alternative Approaches

This is (in my opinion) a less comfortable and less desired way of fixing it, which is making a UI button that activates the afterburner when pressed. 

It is a completely different approach to fix the issue since the button will just activate the afterburner when pressed and will remain unactive when it is not pressed.

It's less comfortable because the player will have to hold a finger in an awkward position **_and it may have issues with other controls since holding two spots on the screen at once completely nullifies any input._**

**Comment by thewierdnut** [comment]
I can probably fix the "two spots" problem, but having a separate button will be awkward, and the button panel space is already crowded. 

I also don't see using afterburners automatically, as they use up fuel that would otherwise be reserved for hyperspace jumping. A long-running fight in a system without a spaceport could exhaust your supply quickly. 

My ultimate goal is a game that can be reasonably played with one thumb. What about a double-tap to activate the afterburner, and it stays active as long as your finger is on the screen?

**Comment by YiffLord** [comment]
> I can probably fix the "two spots" problem, but having a separate button will be awkward, and the button panel space is already crowded.
> 
> I also don't see using afterburners automatically, as they use up fuel that would otherwise be reserved for hyperspace jumping. A long-running fight in a system without a spaceport could exhaust your supply quickly.
> 
> My ultimate goal is a game that can be reasonably played with one thumb. What about a double-tap to activate the afterburner, and it stays active as long as your finger is on the screen?

That sounds like a reasonable fix, completely agree with that idea. But what about making it a triple tap? Just because landing in planets is often done by double tapping, aswell as selecting certain things.

No other reason than to avoid afterburning in those scenarios. Like a third tap to confirm.

**Comment by thewierdnut** [comment]
From a usability perspective, I think a double-tap is something people might expect to exist, but I don't know of any apps that use a triple tap. 

The double-tap would also have to be on an area of unused space, just like the current move command, so presumably it wouldn't be mistaken as a tap on a planet.

**Comment by YiffLord** [comment]
Perfect then, looking foward to it.

**Comment by Lawrence-Krystal** [comment]
Couldn't find a way to open a question, but uh. Does the android port have keyboard support? I just ordered a keyboard so I can actually command my mining drones to mine.

**Comment by thewierdnut** [comment]
> Couldn't find a way to open a question, but uh. Does the android port have keyboard support? 

Yes.

**Comment by Lawrence-Krystal** [comment]
Ok.. game doesn't let you build a mining fleet as it would be to unbalanced. I just have to be envious of the a.i mining fleets for now. I hope samrocketman's mining changes get merged with the master so we can have easier mining on Android. Changing the mine button to a harvest button. But this is just my opinion. Love the game, love the port. Keep up the great work. I will have to stick with small ships that can chase asteroid/drops for now.
