### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by Korb** [thewierdnut/endless-mobile#52]
### Problem Description

With pictures Endless Mobile will be able to be shown on the [f-droid.org/en/packages/](https://f-droid.org/en/packages/) and on the main page of the f-droid app. more people will be able to see and find Endless Mobile.

### Related Issue Links

[https://f-droid.org/packages/com.github.thewierdnut.endless_mobile/](https://f-droid.org/packages/com.github.thewierdnut.endless_mobile/)

### Desired Solution

...

### Alternative Approaches

...

**Comment by thewierdnut** [comment]
Hm... Seem to be working to me...

![image](https://user-images.githubusercontent.com/9004013/222920576-e739e4ed-feba-4414-95a5-2e531ce11c9a.png)

![Screenshot_20230304-113744](https://user-images.githubusercontent.com/9004013/222920722-dd6e469c-f3f6-47f6-9226-4c777adadadf.png)

**Comment by Korb** [comment]
Yes, the screenshots are now correctly displayed:

![endless](https://user-images.githubusercontent.com/3509797/222926108-1020b453-d341-4391-8bd5-07b8f357359a.jpg)
