### ISSUE TITLE
on screen controls for larger devices

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#62]
### Problem Description

A larger device is hard to direct a ship by tapping empty space.

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/8577

### Desired Solution

It would be nice if there was an optional on-screen joystick that could be used to control the ship

### Alternative Approaches

?

**Comment by genry718** [comment]
Agree, its very hard to play on current touch controls when u play on large tablet pc. but i'm playing another 2d-space-sims and all them have virtual joy and its good enough

**Comment by thewierdnut** [comment]
as a short-term solution, how does it feel to turn on "Clickable radar display" in the settings, and then use the radar view in the top left corner as if it were a joypad?

**Comment by genry718** [comment]
good idea! i'm ready to give it a try!

**Comment by genry718** [comment]
Played few hours, on 10" screen it hard to NOT touch left-bottom part of screen with my palm but for early-game trading its ok, so now im ready to get my first 1M xD

**Comment by zuckung** [comment]
I target other ships by tapping the radar,  i would miss that. Possible to make that steering radar turn on/off in options?

**Comment by genry718** [comment]
targeting by click now also working and its pain in my ass, tach time i break gesture and click near any ship - i stop moving((

**Comment by genry718** [comment]
targeting by click now also working and its pain in my ass, tach time i break gesture and click near any ship - i stop moving((

**Comment by genry718** [comment]
@thewierdnut 
sorry for stupid q, but how to fire?? and no auto-pilot attack or i missing something?
just get my first 5M by trading and got my first warship, added guns but how to fire lol? no fire-button on screen, clicking to target only switching targets, button "attack" only for fleet

**Comment by johndh** [comment]
I don't think there's a way to manually fire. Just make sure your settings are set to automatically aim and fire, and if you get close enough and point your ship in the right direction, you'll shoot. Keep in mind that most weapons have very limited range. If you have missiles, you'll get a button to toggle them on and off.
![Screenshot_20230405-055413-914~2](https://user-images.githubusercontent.com/692397/230060772-fb648d34-dfc3-4de2-b2f7-964fcb7f2008.png)

**Comment by thewierdnut** [comment]
I've adjusted this behavior slightly with the latest continuous build. Now it will allow you to fire so long as you have a target selected. It is possible change this behavior with a plugin if needed, if somebody wants the ability fire at any time.

**Comment by thewierdnut** [comment]
I just added a new `Onscreen Joystick` option that you can enable in the settings, that should put a control in the bottom left corner that can be used to control the flagship. It would be great if somebody could try it and and let me know if it works ok, and if its position and size are acceptable.

**Comment by zuckung** [comment]
Works. It isn't nice to see it overlapping the ships and the message box, but i dont have a better idea for placement.

**Comment by genry718** [comment]
oh awesome news!

cant install debug version over fdroid's version, is this ok? it just says "not installed"

**Comment by thewierdnut** [comment]
f-droid signs their version with their own key. In order to install the debug version, you will need to uninstall the f-droid version first. Remember to export your savefile first if you want to save your pilot.

**Comment by genry718** [comment]
ah i see. installed latest debug version. now i have option in settings but no joy in game(( left-bottom corner, nothing and on click just directing me there

multitouch works good and gestures also (but on first launch gesturs worked in game but not in options, restart helps).

**Comment by thewierdnut** [comment]
Do you see a new "Onscreen Joystick" option under Preferences->Settings?

![image](https://user-images.githubusercontent.com/9004013/233400441-1add8b9a-9dfa-42e9-a404-241d131b7161.png)

**Comment by genry718** [comment]
yes, its on
![image](https://user-images.githubusercontent.com/100438812/233426641-89d3c614-66e2-41ec-a9ef-71268b7c65d8.png)
![image](https://user-images.githubusercontent.com/100438812/233426662-59a240b1-9c30-4700-92f0-00569a1e16aa.png)

**Comment by thewierdnut** [comment]
I see you have a "Hold" button. Do you have a plugin installed that changes your interfaces? If so, you will need to add the following to the "main buttons" section:
```
	# box in bottom left corner that defines a location for the onscreen joystick
	anchor bottom left
	box "onscreen joystick"
		center 128 -128
		dimensions 192 192
```

I've added a few controls recently, most of them either invisible or layered transparently on top of existing ui elements: 

https://github.com/thewierdnut/endless-mobile/blob/android/data/interfaces.txt#L1444-L1471

**Comment by genry718** [comment]
Works good!

Also i find another interesting control method in another space game, maybe u interested it

https://user-images.githubusercontent.com/100438812/233448706-635be56c-62f5-4c34-a812-0cc69063cb6e.mp4

**Comment by zuckung** [comment]
Had the same problem with thewirednuts plugin workaround a few updates before, till i found out that the plugin owerwrites interfaces changes he was recently doing.

So i think you still miss 3 more features with that "outdated" plugin.

add this to the plugin.

```
# Overlayed on target display, but the hud doesn't have a panel, so to	
# handle input, we put it here instead.	
	visible
	active
	anchor top left	
	button "Select next ship"
		center 75 315
		dimensions 50 50

# Overlayed on the navigational panel, which displays something like	
# "Can land on: Earth"	
	visible
	active	
	button "Land on planet / station"
		from 200 0 to 380 60

# hidden button in top-left corner that turns on fast-forwarding	
	visible
	active
	anchor top left	
	button "Toggle fast-forward"
		from 0 0 to 48 48
```

Fast forward at the Top left corner is my favorite :)
