### ISSUE TITLE
Unable to reorder ships on the player info page

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The player info page has a list of ships, and you should be able to reorder them. This works on a desktop build, but not on an android device. 

### Steps to Reproduce

Open the player info dialog when you have more than 3 ships, try and arrange their order.

### Expected Behavior

you can change the order of the ships

### Device type

asdf

### Game Version

asf

**Comment by zuckung** [comment]
That would be nice. And please add scrolling there(and in other overviews, like at outfitter/shipyard).

**Comment by thewierdnut** [comment]
After some finagling, I *can* reorder ships from this page, but the drag-and drop logic seems to get stuck on with a touch screen, and it breaks the park button.

**Comment by thewierdnut** [comment]
So it looks like this gui is broken because it relies on mouse hover to establish the pointer position prior to all drag events. It also doesn't impelment a drag scroll, instead only using the scroll wheel. 

I'm going to have to reimplement all of that logic using touch events instead.

**Comment by zuckung** [comment]
Well done. Want the outfitter/shipyard scrolling as own issue? You know, when u have more than 44 ships there is no free space for tap-pull scrolling?

**Comment by thewierdnut** [comment]
Yes please. Each of these user interfaces implements scrolling  differently, so I have to change them all separately.
