### ISSUE TITLE
Attack button does not also trigger fire

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#66]
>sorry for stupid q, but how to fire?? and no auto-pilot attack or i missing something?
just get my first 5M by trading and got my first warship, added guns but how to fire lol? no fire-button on screen, clicking to target only switching targets, button "attack" only for fleet
>_Originally posted by @genry718 in https://github.com/thewierdnut/endless-mobile/issues/62#issuecomment-1494172984_

I'm pretty sure this used to work. I'll take a look

**Comment by thewierdnut** [comment]
@genry718

In the meantime, if `Automatic firing` is on in preferences (it should be on by default in this port), your ship should automatically fire on anything your fleet has targeted. This works pretty well for turrets, but for guns you have to make sure your ship is facing the right direction. 

Oddly enough, this doesn't work if you don't have a fleet, but it *does* work if your entire fleet is parked.

**Comment by genry718** [comment]
tested, yep, its works
