### ISSUE TITLE
outfit "puny" vanishes on app close

### ISSUE THREAD

**Issue by zuckung** [thewierdnut/endless-mobile#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The unique dog outfit "puny" vanishes when closing the app. Happends on swipe close, external kill app and with the quit button ingame. I have some plugins installed, but dont think anything touches puny. When editing it back into save i use the correct form `"Puny"`. Official ES github don't has this issue.

I m a bit afraid i edited in wrong, but cant find a mistake.

### Steps to Reproduce

1. Have puny installed in flagship
2. Exit game

### Expected Behavior

Puny should stay

### Link to save file

[Zap Brannigan_exported.txt](https://github.com/thewierdnut/endless-mobile/files/11233454/Zap.Brannigan_exported.txt)

### Device type

galaxy tab a6 / android 8.1

### Game Version

0.10.0

**Comment by thewierdnut** [comment]
you say you have edited this save? I see two variants of "Puny" in your save:
```
	outfits
		`"Puny"`
		...
		Puny 2
```

**Comment by thewierdnut** [comment]
It looks like this was fixed after the 0.10.0 release (which is what the current android branch is based on). I'll go ahead and cherry-pick the fix. 

https://github.com/endless-sky/endless-sky/pull/8546

**Comment by zuckung** [comment]
Whoops i ment the first, the 2nd was testing which ich forgot to remove. And it seems that the 2nd has no effect at all. After removing the 2nd, the Problem is the same. Thanks for fixing

**Comment by thewierdnut** [comment]
Hm... Its really really tempting to give that dog a "capture attack"/"capture defense" of .2 or something

**Comment by zuckung** [comment]
:) just do it

**Comment by zuckung** [comment]
Just found out, the second  puny outfit in my save is generated each time a puny outfit gets removes by the game. So not my fault^^
