### ISSUE TITLE
Using Secondary Weapon Systems

### ISSUE THREAD

**Issue by larrydewey** [thewierdnut/endless-mobile#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After purchasing some meteor missles, I found I wasn't able to use them, nor any secondary weapons. On the computer version, there is an option to select the secondary weapon/ammunition, but on mobile the jump and map buttons cover the weapon selection. If this is already something which can be done, perhaps adding some documentation?

### Steps to Reproduce

1. Load a game where your ship has secondary weapons.
2. Target an asteroid or enemy vessel.
3. Attempt to fire secondary weapon systems.
4. No action happens.

### Expected Behavior

A simple way to either manually fire secondary weapons, or build in secondary weapons into the automatic firing system.

### Operating System

Phone: Android 12  Laptop: Linux - Kernel 5.19.7-zen2-1-zen

### Game Source

GitHub Releases

### Game Version

26 Debug

**Comment by thewierdnut** [comment]
At the moment, there is no way to fire the secondary weapons. The auto-fire logic will not use expendable ammo, and there is no way without a keyboard to switch which secondary weapon is selected. The weapons game logic is rather complicated, so I have opted so far not to mess with it, as it makes rebasing on the upstream repo more difficult. 

If I put a secondary fire button on the screen, I probably also need to put a secondary weapon selector. The flight screen is already cluttered, and it would be difficult to switch back and forth between controlling your ship and controlling your weapons with a touchscreen. This is the simpler, easier-to-maintain option. 

An alternative would be to just add secondary weapons to the auto-fire system, which would give you less control, but you could focus on flying. I can probably re-use the existing logic, used for escorts though. This option would require several hooks in the ai logic, and will likely cause many merge conflicts in the future.

**Comment by larrydewey** [comment]
I would imagine the secondary button options would make sense. I am not familiar with the UI options, but would it be possible to implement a drag type context menu? This way you would be able to store a number of options under an individual button. I am by no means a UI/UX person, but this is kind of what I was invisioning.

![drag-menu](https://user-images.githubusercontent.com/41640198/194934208-7b9d856f-b658-4133-9be6-902495ec5dd4.svg)

**Comment by thewierdnut** [comment]
That isn't a bad idea, but it would have to be implemented completely from scratch, as endless-sky uses a custom toolkit.

**Comment by thewierdnut** [comment]
I think its very rare though that you would have more than two secondary weapons. A simple toggleable icon might make more sense.

**Comment by larrydewey** [comment]
That makes sense, and is a very valid point. I was thinking that it might be beneficial for collapsing down some of the other buttons on the screen. Maybe a compass rose icon which contains jump, map, targeting, etc. Just an idea, though. Whatever you feel would be the best. I am not privy to the toolkit or how much work it would take.

**Comment by thewierdnut** [comment]
The "toolkit" is literally a bunch of png files that you can click on. I basically have nothing to work with but vanilla buttons.

**Comment by thewierdnut** [comment]
This should be fixed by 10eff37038a72cfcf7a069f11c66067188ebb40f let me know if this works for you.

**Comment by larrydewey** [comment]
Yep, this provides a solution for now. Thanks!
