### ISSUE TITLE
Crash when toggling the new gesture control settings.

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When selecting/toggling/even touching the control settings that are defaulted to gestures, the game simply crashes.

### Steps to Reproduce

1. Go to control settings.
2. Click on any gesture defaulted control.
3. Success: see crash.

### Expected Behavior

Expected not to crash.

### Device type

Overclocked Samsung Tab S2 9.7

### Game Version

Build 33

**Comment by thewierdnut** [comment]
Ouch, yes I can reproduce this. Thanks for reporting. 

As a workaround, if you clear the gesture (just tap anywhere with it selected), then you can set it to whatever you want without crashing.

**Comment by YiffLord** [comment]
> Ouch, yes I can reproduce this. Thanks for reporting.
> 
> As a workaround, if you clear the gesture (just tap anywhere with it selected), then you can set it to whatever you want without crashing.

The gesture controls are such a great implementation.
I would just like to customize the ones such as the _"X"_ to simpler and quicker ones.

Edit: Okay there has been a misunderstanding by my part, it's late here and I have my mind on other galaxy right now. Forget the first reply line. Here I'll delete it. Done.

**Comment by thewierdnut** [comment]
Lol. One of my long term goals is a button that allows you to train it to recognize new gestures, or to add more examples of existing ones. The current templates are hand-coded, with a pretty high threshold for recognition.

**Comment by YiffLord** [comment]
I realised that some gestures work better or are required to be done from right to left instead of left to right. Nothing to be considered an error or similar but I thought I'd mention it going with your reply.

**Comment by thewierdnut** [comment]
I put left and right handed versions of each gesture into the template table. They should all be symmetrical, though its entirely possible I did it wrong.

**Comment by YiffLord** [comment]
By the way I wanted to thank you for the work you put into this. I don't think many people would do this kind of effort to push the compatibility of a PC game into mobile. It's great to see how many improvements are being done with each release aswell.

**Comment by thewierdnut** [comment]
Thank you. I'll admit I've played through the game enough times that my interest in it as a game is waning. However, enthusiasm from players makes it more interesting as a coding project, so I appreciate it.
