### ISSUE TITLE
Basic trading stuff.

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#75]
### Problem Description

The port trader is so aggresively persuasive that they only let you buy in bulk, or go through the tedious process of confirming a 1 ton purchase hundreds of times.
/
![Screenshot_20230422-225101](https://user-images.githubusercontent.com/89931675/233806488-1c3e039f-01c0-4db3-b85c-4b3ce40d4290.jpg)
![Screenshot_20230422-225118](https://user-images.githubusercontent.com/89931675/233806489-0240b2e8-0526-4d30-a41d-8e3ad0edf1c7.jpg)

### Related Issue Links

Nothing.

### Desired Solution

Add something in the planet trading area where a value can be typed or selected. The same way or similar to the loan input / outfit purchase amount.

### Alternative Approaches

Dunno.

**Comment by thewierdnut** [comment]
Normally you are meant to hold down some combination of ctrl/alt/shift here to put a modifier on the buy/sell button. This obviously won't work on devices without a keyboard though. 

The same problem exists on the hire/fire page, though a simple "hire all" button might suffice there.

**Comment by YiffLord** [comment]
A _**Hire all**_ button will do the trick.
