### ISSUE TITLE
Land Button

### ISSUE THREAD

**Issue by ZeroPoke** [thewierdnut/endless-mobile#77]
### Problem Description

Its not fun trying to find the planet and then fly over there a tap on it.  Especially when you have a Mission and there are more then one planets in the system.

### Related Issue Links

I dont know

### Desired Solution

Add a button to the main game screen next to like Jump that activates Endless Sky Landing function.

### Alternative Approaches

I dont know

### Additional Context

When playing on my Steam Deck, I just press my landing button, almost never fly to the planet my self.  Makes life alot easier.

**Comment by YiffLord** [comment]
Pro tip, when selecting a system to navigate to in the map, click on the end location's desired planet/station to land and when you arrive there it will land automatically.

**Comment by thewierdnut** [comment]
If you have build 33 or newer, you can use the Navigation panel as a land button. Just tap this near the top-left corner: 

![image](https://user-images.githubusercontent.com/9004013/233815764-a9765c0b-abc6-45b1-8e80-c74dfbc6ac26.png)
