### ISSUE TITLE
Multitouch & joy

### ISSUE THREAD

**Issue by genry718** [thewierdnut/endless-mobile#79]
### Problem Description

After last update we have multitouch, its very cool and needed feature just becouse in battle each time u press buttons or targeting - u stop engines.
Also vitrual on screen joy imlemented, its awesome for large screens!

but this two don't work together :( multitouch works for all except new joy.

### Related Issue Links

no

### Desired Solution

multitouch works together with joy

### Alternative Approaches

no

**Comment by thewierdnut** [comment]
Can you provide more detail on what seems to be broken? It feels like it is working ok to me.

**Comment by MonkeyMatrix** [comment]
The multi-touch with onscreen joystick works fine for me. I was able to perform all the functions available with no onscreen joystick.
