### ISSUE TITLE
New simple gestures

### ISSUE THREAD

**Issue by genry718** [thewierdnut/endless-mobile#81]
### Problem Description

Just "to left then to right", "to up then to down" without angle/arrow - think its much easy to draw this in courage of battle :)

### Related Issue Links

no

### Desired Solution

new more simpler gestures

### Alternative Approaches

dont know

**Comment by YiffLord** [comment]
These kind of gestures are so simple and generic they may interfere with normal gameplay. Moving or aiming at an enemy could trigger unwanted orders easily.

**Comment by thewierdnut** [comment]
There is a balance between having gestures simple to draw and recognize, vs accidentally triggering them. Unfortunately a lot of it maybe comes down to user preference. 

My long term goal is to add user definable symbols, but that will involve the creation of a new user interface that will let you train the symbol recognizer. That is not coming soon though.

**Comment by genry718** [comment]
my main idea was to use this simple gestures only with this option https://github.com/thewierdnut/endless-mobile/issues/80

**Comment by thewierdnut** [comment]
I'm gonna close this. I don't think it will work to have such simple gestures, as they would be too easy to trigger accidentally. Eventually, I plan to have user-specified gestures, which would basically support this if the user wants.
