### ISSUE TITLE
Ability to deselect ship in fleet (in main game screen)

### ISSUE THREAD

**Issue by genry718** [thewierdnut/endless-mobile#83]
### Problem Description

cant select ship in fleet but second click dont deselect it

in this case after selecting - i cant anymore control antire fleet, only 1-by-1

is this bug on me and i need bug report?

### Related Issue Links

no

### Desired Solution

no

### Alternative Approaches

no

**Comment by thewierdnut** [comment]
I haven't implemented most of the fleet commands yet. As a workaround for the selection issues though, you can deselect all by tapping on your flagship.

**Comment by roelfrenkema** [comment]
Problem is when selling ships you frequently end up selling you flag ship because 2 are selected.

**Comment by thewierdnut** [comment]
> Problem is when selling ships you frequently end up selling you flag ship because 2 are selected.

This is a separate issue, but one that annoys me too.
