### ISSUE TITLE
Ship Selection Bug in Outfitter and Shipyard

### ISSUE THREAD

**Issue by Nidstangesq** [thewierdnut/endless-mobile#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The most recent update appears to have introduced a bug whereby you can no longer select individual ships in the Shipyard or Outfitter, making selling ships and installing/selling outfits virtually impossible. 
When you enter either the Outfitter or the Shipyard your flagship is pre-selected, and tapping other ships selects them as well so you have multiple ships selected -- there is no way to deselect any ship.

### Steps to Reproduce

1. Go to Shipyard or Outfitter 
2. Click on any ship in your fleet to select it 
3. Now you have multiple ships selected, and there is no way to deselect any ship

### Expected Behavior

You should be able to select individual ships in your fleet by tapping on them in the Outfitter and Shipyard views.

### Link to save file

https://www.dropbox.com/s/wi90x8pnoe7gslq/Shaitan%20K._exported.txt?dl=0

### Device type

Samsung SM-T500

### Game Version

v0.10.0-33

### Additional Information

No other information, but thank you so much for all your hard work on this project. The game is awesome.

**Comment by thewierdnut** [comment]
I can't reproduce this. It seems to work as expected. 

How are you trying to select multiple ships? It uses a 500ms long finger press, though you should probably tap for a full second just to make sure.

**Comment by Nidstangesq** [comment]
I'm not trying to select multiple ships.  I'm trying to select a single ship, but when I enter the Outfitter/Shipyard the flagship is already pre-selected.  I can't deselect the flagship, and anytime I try to tap a different ship it just adds it as a multi-select.

**Comment by thewierdnut** [comment]
hm... a fast tap should single select whatever ship you are tapping on. There must be something different about your setup 

Does the broken behavior persist after a hard shutdown and restart of your device? 
Do you have a keyboard of some kind?
Are you using a stylus or something similar?

**Comment by Nidstangesq** [comment]
No stylus, keyboard, joystick, etc.

That said, I cleared cache and rebooted and now I can deselect a ship by tapping on it.  That's different than the pre-update behavior (before, tapping ship #2 would deselect ship #1 -- now, tapping ship #2 keeps both #1 and #2 selected) but it's totally workable.

Thanks again for all your work on this.

**Comment by mavaa** [comment]
@thewierdnut I think I'm having this issue, or something very similar. Tried all the tips here as well as your [comment](https://github.com/thewierdnut/endless-mobile/issues/92#issuecomment-1646733837) about custom behaviours, but they don't seem to work. For me:

- A double tap selects multiple ships as you described
- A long tap adds the ship to the selection, no matter how long I hold it
- Tapping an unselected ship adds it to the selection, no matter how many others are selected, and tapping a selected ship doesn't unselect it

I'm also seeing that any tap, long or short seems to trigger some drag-and drop as well, letting me move ships around, so maybe some other change here has made the long/short tap stop working? Just say so if I should make a separate issue instead.

Running the latest f-droid release on a Fairphone 4 with DivestOS (no Google apps), but I think/hope that's not relevant.

**Comment by thewierdnut** [comment]
This is fixed on build 45, which was released yesterday, and probably won't land on f-droid for another week or so.
