### ISSUE TITLE
I can't seem to find a way to support your efforts for this fork?

### ISSUE THREAD

**Issue by dilydaly** [thewierdnut/endless-mobile#86]
### Location

Android fork of Endless Sky

### Describe the issue

I deeply enjoy this game and have been playing it for over half a decade now. I am much too busy to contribute correctly to the android build, but I wish to support your efforts. 

Aside from filing bugs and feature requests, how else can I contribute to this fork?

### Expected content

Do you have a KoFi or Patreon or something?

**Comment by YiffLord** [comment]
I haven't seen any patreon link or anything similar so I don't think there is, don't quote me on that though.

Since (as far as I know) there isn't such, I thanked the dev and share the game as much as possible, without being obnoxious ofcourse.

**Comment by thewierdnut** [comment]
My personal situation, which I suspect is true for most programmers, is not a lack of money, but a lack of time. The hardest thing for me to do is to test the program adequately, and so playing the game, looking for bugs, and filing issues *is* the best way to support this project for now. 

I do admit that just expressing appreciation means a lot. I've seen enough derogatory comments on discord about this "janky" port that it gets a little disheartening sometimes.
