### ISSUE TITLE
Checking in :)

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#87]
### Problem Description

Man it's hard to believe that this port was done all by one individual as a hobby or side project, just putting in their own time to make a great yet simple game available for more users that can't play the original PC one. 

The game evolves with each small update, and it gets better every time, thanks :)

### Related Issue Links

/

### Desired Solution

/

### Alternative Approaches

/

**Comment by thewierdnut** [comment]
You're welcome!
