### ISSUE TITLE
Boarding

### ISSUE THREAD

**Issue by roelfrenkema** [thewierdnut/endless-mobile#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Is boarding implemented yet? I need to board the surveylance drone after disabling it but I have no clue how. 

### Expected Behavior

A boarding option lower right corner

### Device type

Moto edge

### Game Version

Latest

**Comment by thewierdnut** [comment]
Unable to reproduce. 

You can board ships by tapping on them. You can also assign a gesture to the board command in the preferences.
