### ISSUE TITLE
Problem is when selling ships you frequently end up selling you flag ship because 2 are selected.

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#89]
Problem is when selling ships you frequently end up selling you flag ship because 2 are selected.

_Originally posted by @roelfrenkema in https://github.com/thewierdnut/endless-mobile/issues/83#issuecomment-1625686442_

**Comment by danhoffpauir** [comment]
When this happens, I reload my last save immediately

**Comment by thewierdnut** [comment]
That's about the only thing you *can* do. I think a popup warning you that you are selling your flagship when you have more than one ship selected would work, but would be annoying. An undo button would be better, but would be harder to implement. 

These types of UI changes are usually better implemented upstream, but there may not be an appetite there as it is harder to inadvertently select extra ships.

**Comment by johndh** [comment]
It seems to me that there is too little difference between clicking on a ship to select it, and clicking on it for very slightly longer to add it to the current selection.

**Comment by thewierdnut** [comment]
I've raised this issue upstream where solutions are being considered. I'm closing this issue for now.
