### ISSUE TITLE
Add support for importing/exporting save files

### ISSUE THREAD

**Issue by rediris** [thewierdnut/endless-mobile#9]
### Problem Description

It would be nice to have the option of accessing the save game .txt files - whether to import or export. There's currently no way of accessing those files in android without rooting one's phone.

### Related Issue Links

N/A.

### Desired Solution

* Save game file would be accessible in Android's files app (internal storage)
* The in app menu would have an option to import and export save game files

### Alternative Approaches

N/A

**Comment by thewierdnut** [comment]
Duplicate of #6 

Presumably this will get updated on f-droid eventually.

**Comment by thewierdnut** [comment]
Duplicate of #6
