### ISSUE TITLE
Outfit scan pop-up is not scrollable, cuts off if longer than screen height

### ISSUE THREAD

**Issue by danhoffpauir** [thewierdnut/endless-mobile#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Outfit scan pop-up is not scrollable, cuts off if longer than screen height, hiding the expected buttons that appear at the bottom of the pop-up.

This makes it impossible to complete the Free Worlds Reconnaise job, obtained in the spaceport of Glaze in the Aldibhain system, for the Free Worlds. 

### Steps to Reproduce

1. Load my save or obtain the quest Free Worlds Reconnaissance. Install outfit scanners. 
2. Fly to Menkent system
3. Scan one of the flashing Republic ships. 
4. See impassable pop-up bug

### Expected Behavior

Ability to click a button to continue after outfit scan

### Screenshots

![Screenshot_20230708-231625](https://github.com/thewierdnut/endless-mobile/assets/7836046/56f7c0a8-f1e1-43f7-813c-e0e793670e0b)
![Screenshot_20230708-232653](https://github.com/thewierdnut/endless-mobile/assets/7836046/7c4c9467-38df-4dfc-8922-2b953acb06a8)

### Link to save file

[Jack Hoff_exported (1).txt](https://github.com/thewierdnut/endless-mobile/files/11994323/Jack.Hoff_exported.1.txt)

### Device type

Google Pixel 4a 5g

### Game Version

0.10.2

### Additional Information

Installed via F-droid

**Comment by thewierdnut** [comment]
I'll find a solution for this. In the meantime, you can work around it by hitting the android back button, which can be revealed by swiping from the side, or by turning off fullscreen in the settings.
