### ISSUE TITLE
ammo counters are covered by map buttons

### ISSUE THREAD

**Issue by thewierdnut** [thewierdnut/endless-mobile#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The ammo counters for secondary weapons are hiding underneath the map buttons in the bottom right corner

### Steps to Reproduce

get a ship with secondary weapons, and got to the screen. you can see them being drawn underneath the buttons

### Expected Behavior

They should probably be moved somewhere more useful: 
![image](https://github.com/thewierdnut/endless-mobile/assets/9004013/318d3344-94c2-4d59-a05f-b2b98b70422f)

Keep in mind that moving the bounding box isn't quite sufficient, as the secondary weapons are drawn from the bottom up in order, making aligning them to the top of the screen difficult, as we don't know how many weapons the user has. We will need to allow ammo display to modify its drawing direction depending on the aligned screen boundary. 

### Device type

asdf

### Game Version

37

**Comment by thewierdnut** [comment]
It turns out these are drawn on accident. They are supposed to be disabled by the "Show buttons on map" preference, which got botched and disabled by a merge. 

I'm going to restore the original behavior (which was not to draw them at all if the buttons are there), and if somebody needs them somewhere else, lets create a new issue for it.

**Comment by YiffLord** [comment]
Alright, sounds like a fair idea to me.
