### ISSUE TITLE
put the .apk on github for obtainium to see

### ISSUE THREAD

**Issue by RustoMCSpit** [thewierdnut/endless-mobile#95]
### Problem Description

..

### Related Issue Links

n/a

### Desired Solution

.

### Alternative Approaches

none?

**Comment by thewierdnut** [comment]
I'll need more detail than that. Both the release and continuous apks are on the releases page. 

https://github.com/thewierdnut/endless-mobile/releases

**Comment by RustoMCSpit** [comment]
> I'll need more detail than that. Both the release and continuous apks are on the releases page.
> 
> https://github.com/thewierdnut/endless-mobile/releases

oh shoot they just didnt load for me

**Comment by RustoMCSpit** [comment]
close this issue thanks

**Comment by ClockGen** [comment]
@thewierdnut it seems that currently CI signs apks with a new key with each build, so they can't be updated anyway, only with full uninstall first.

**Comment by thewierdnut** [comment]
They are debug apk's, which means they are signed with the android debug key. They will not be compatible with f-droid releases, which are signed with f-droid's own key (which I don't have access to).

You should be able to upgrade from the github apks to the next github apk, but switching back and forth from the github apks to the f-droid apks will require an uninstall first.

**Comment by ClockGen** [comment]
I'm talking about github debug builds. I can't upgrade any of them, even if versionCode increments.

**Comment by zuckung** [comment]
A workaround  for us users would be 
https://play.google.com/store/apps/details?id=com.haibison.apksigner&hl=de&gl=US

Very easy to use, sign apk, install, on every update do a 2 minute signing on the apk, update install works.

**Comment by thewierdnut** [comment]
That doesn't help with obtanium though. 

So I hoped to avoid this issue by using the debug key generated by the android build process, and that works for my purposes, but when I build this on github, it starts with a fresh build image every time, which means the build makes a new key for every apk. 

I don't really want to get into the business of managing keys, as I don't want to post them as part of the repo, and I don't want to have to manually sign and update each build, so I'm kind of at a loss for a way forward at the moment.

**Comment by thewierdnut** [comment]
> I'm talking about github debug builds. I can't upgrade any of them, even if versionCode increments.

I think this is fixed now, though old (and current) builds will still be broken. Future builds should work though.
