### ISSUE TITLE
Easier fleet management.

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#97]
### Problem Description

I'm always frustrated when the fleet selection divides itself in space if the fleet size is below 12 ships, regardless of type. For example, you have 3 Hawks and 4 Star Barges, you'd have to select each ship individually. Or if you have, say 322 Arach Hulks and 5 Albatross, the Albatross will be divided aswell.

![Screenshot_20230819-230209](https://github.com/thewierdnut/endless-mobile/assets/89931675/4ecef4e0-f22f-4a0f-bb26-7edca1c28738)

### Related Issue Links

/

### Desired Solution

Group all ships of the same type regardless of how many there are in the same way that it happens when you have a large fleet. 

This will make giving commands something viable instead of having a situation where you have to pick and give commands ~8 times while something of magnitude is happening (Reason why the commands are needed).

![Screenshot_20230819-230751](https://github.com/thewierdnut/endless-mobile/assets/89931675/dff47be1-6b3a-45b6-a4a8-7440e2491429)

### Alternative Approaches

I don't know, but as long as it fixes it it's awesome.

### Additional Context

_Painful small fleet management..._

**Comment by thewierdnut** [comment]
I agree. I need to rewrite the code that generates those icons. On my device, That list is unusable, as it usually only ever shows one ship anyways due to limited screen space.

**Comment by YiffLord** [comment]
> I agree. I need to rewrite the code that generates those icons. On my device, That list is unusable, as it usually only ever shows one ship anyways due to limited screen space.

On large screens (Tablets) that doesn't seem to be an issue at all, thankfully.
