### ISSUE TITLE
plugin window doesn't cut text

### ISSUE THREAD

**Issue by zuckung** [thewierdnut/endless-mobile#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The list of installed plugins and the plugin description don't get cut of at the end of the window. 

### Steps to Reproduce

1 install many plugins
2 see result

![Screenshot_20230902-190516_Endless Sky](https://github.com/thewierdnut/endless-mobile/assets/27899515/1acf0bf9-ae84-4e7c-ad96-c1ee6fb40870)

### Expected Behavior

The text should be cut off at the borders of the window and a scroll bar should appear, or tap-hold scrolling.

### Device type

galaxy tab a6

### Game Version

0.10.2

**Comment by thewierdnut** [comment]
This needs fixed upstream. 

https://github.com/endless-sky/endless-sky/issues/2022
